# backend/Dockerfile
FROM node:18-alpine

WORKDIR /usr/src/app

COPY package*.json ./
# Usamos 'npm ci' en lugar de 'npm install' para builds de producción.
# Es más rápido y seguro porque usa el package-lock.json.
RUN npm ci --only=production

COPY . .

# Corregimos el puerto para que coincida con el de nuestro servidor Express (5001)
EXPOSE 5001

CMD ["node", "index.js"]